configuration/globalcfg.py.sample added
codex-team/codex.bot.v3 pull request #2
Opened 2017-02-12 10:19 UTC by scytem

without tokens and url

2017-02-12 10:21 UTC, neSpecc commented on configuration/globalcfg.py.sample
> +URL = 'https://...'
можешь тут в комментах еще написать, что обязателен слэш в конце? и `'https://.../'`

2017-02-12 12:44 UTC, n0str commented on configuration/globalcfg.py.sample
> +            'ID': '', # '',
Убери # и то, что после нее. Это ненужные комментарии.

2017-02-21 15:10 UTC, n0str commented
@scytem доделаешь?

2017-02-22 10:18 UTC, neSpecc requested changes

2017-02-22 10:18 UTC, neSpecc commented on configuration/globalcfg.py.sample
> +# Копируйте ваш URL из ngrok и не забудьте '/' в конце
суть не в ngrok, а в том, чтобы был слэш в конце. ngrok это частный случай локальной разработки, он не относится к проекту

2017-02-22 10:23 UTC, n0str requested changes

2017-02-22 10:23 UTC, n0str commented on configuration/globalcfg.py.sample
> +            'ID': '', # '',
Убери эти решетки, они не нужны. 'ID': ''

2017-02-22 17:14 UTC, n0str commented
Принято, но устарело.

2017-02-22 17:14 UTC, closed without merging